function [globalInfos] = initLstmInfosStruct(numTests, numRepeats)

globalInfos = struct(...
    'TrainingLoss', cell(numTests, numRepeats), ...
    'TrainingAccuracy', cell(numTests, numRepeats), ...
    'ValidationLoss', cell(numTests, numRepeats), ...
    'ValidationAccuracy', cell(numTests, numRepeats), ...
    'BaseLearnRate', cell(numTests, numRepeats), ...
    'FinalValidationLoss', cell(numTests, numRepeats), ...
    'FinalValidationAccuracy', cell(numTests, numRepeats));
end